export const nama_barang = [
  { nama: "Laptop ASUS" },
  { nama: "Laptop Dell" },
  { nama: "Laptop HP" },
  { nama: "Monitor Samsung" },
  { nama: "Monitor LG" },
  { nama: "Keyboard Logitech" },
  { nama: "Keyboard Microsoft" },
  { nama: "Mouse Razer" },
  { nama: "Mouse Logitech" },
  { nama: "Printer Canon" },
  { nama: "Printer Epson" },
  { nama: "Router TP-Link" },
  { nama: "Router D-Link" },
  { nama: "Hard Disk Seagate" },
  { nama: "SSD Samsung" },
  { nama: "RAM Kingston" },
  { nama: "RAM Corsair" },
  { nama: "CPU Intel" },
  { nama: "CPU AMD" },
  { nama: "Power Supply Corsair" },
  { nama: "Motherboard ASUS" },
  { nama: "Motherboard MSI" },
  { nama: "Graphics Card NVIDIA" },
  { nama: "Graphics Card AMD" },
  { nama: "Headset SteelSeries" },
  { nama: "Headset HyperX" },
  { nama: "Speaker JBL" },
  { nama: "Webcam Logitech" },
  { nama: "Microphone Blue Yeti" },
  { nama: "UPS APC" },
  { nama: "Laptop Lenovo" },
  { nama: "Laptop Acer" },
  { nama: "Monitor Dell" },
  { nama: "Monitor HP" },
  { nama: "Keyboard Razer" },
  { nama: "Keyboard Corsair" },
  { nama: "Mouse Logitech G" },
  { nama: "Mouse SteelSeries" },
  { nama: "Printer Brother" },
  { nama: "Printer HP DeskJet" },
  { nama: "Router Linksys" },
  { nama: "Router Asus" },
  { nama: "Hard Disk WD" },
  { nama: "SSD Kingston" },
  { nama: "RAM G.Skill" },
  { nama: "RAM Crucial" },
  { nama: "CPU Ryzen" },
  { nama: "CPU Intel Core i9" },
  { nama: "Power Supply EVGA" },
  { nama: "Motherboard Gigabyte" },
  { nama: "Graphics Card ASUS GeForce" },
  { nama: "Graphics Card MSI Radeon" },
  { nama: "Headset Logitech G Pro" },
  { nama: "Headset Sennheiser" },
  { nama: "Speaker Bose" },
  { nama: "Webcam Microsoft" },
  { nama: "Microphone Rode" },
  { nama: "UPS CyberPower" },
  { nama: "External HDD Seagate" },
  { nama: "External SSD Samsung T5" },
  { nama: "Wireless Mouse Microsoft" },
  { nama: "Wireless Keyboard Logitech" },
  { nama: "Portable Printer Canon Pixma" },
  { nama: "Smartphone Samsung Galaxy" },
  { nama: "Tablet Apple iPad" },
  { nama: "Gaming Chair DXRacer" },
  { nama: "Desk Lamp Philips Hue" },
  { nama: "Digital Camera Canon EOS" },
  { nama: "Action Camera GoPro Hero" },
  { nama: "Fitness Tracker Fitbit Versa" },
  { nama: "Smartwatch Apple Watch" },
  { nama: "Bluetooth Speaker JBL Flip" },
  { nama: "Wireless Earbuds Sony WF" },
  { nama: "Gaming Mousepad SteelSeries QcK" },
  { nama: "Gaming Keyboard Razer BlackWidow" },
  { nama: "Gaming Monitor ASUS ROG Swift" },
  { nama: "Gaming Headset HyperX Cloud" },
  { nama: "Gaming Chair Secretlab Titan" },
  { nama: "Wireless Router Netgear Nighthawk" },
  { nama: "Wireless Earbuds Apple AirPods" },
  { nama: "Wireless Charging Pad Anker PowerWave" },
  { nama: "Wireless Presenter Logitech Spotlight" },
  { nama: "Wireless Keyboard Apple Magic Keyboard" },
  { nama: "Wireless Mouse Apple Magic Mouse" },
  { nama: "Wireless Router Google Nest WiFi" },
  { nama: "Bluetooth Earphones Bose QuietComfort" },
  { nama: "Bluetooth Speaker Bose SoundLink" },
  { nama: "Bluetooth Headphones Sony WH" },
  { nama: "Bluetooth Keyboard Logitech K380" },
  { nama: "Bluetooth Mouse Microsoft Surface" },
  { nama: "Wireless Charger Samsung Wireless Charger" },
  { nama: "Wireless Headphones Sennheiser Momentum" },
  { nama: "Wireless Gaming Mouse Logitech G Pro" },
  { nama: "Wireless Gaming Keyboard Corsair K63" },
  { nama: "Wireless Gaming Headset SteelSeries Arctis" },
  { nama: "Wireless Gaming Controller Xbox Wireless Controller" },
  { nama: "Bluetooth Gaming Headset Turtle Beach Stealth" },
  { nama: "Bluetooth Gaming Mouse Razer Atheris" },
  { nama: "Bluetooth Gaming Keyboard Roccat Vulcan" },
  { nama: "Bluetooth Gaming Headset HyperX Cloud Flight" },
  { nama: "Bluetooth Gaming Controller SteelSeries Nimbus" },
  { nama: "Bluetooth Gaming Mouse Logitech G305" },
  { nama: "Bluetooth Gaming Keyboard Corsair K55" },
  { nama: "Bluetooth Gaming Headset Razer Nari" },
  { nama: "Bluetooth Gaming Controller Sony DualShock" },
  { nama: "Bluetooth Gaming Mouse Asus ROG Gladius" },
  { nama: "Bluetooth Gaming Keyboard Logitech G613" },
  { nama: "Bluetooth Gaming Headset Astro A50" },
  { nama: "Bluetooth Gaming Controller Nintendo Switch Pro" },
  { nama: "Bluetooth Gaming Mouse HyperX Pulsefire Dart" },
  { nama: "Bluetooth Gaming Keyboard HyperX Alloy FPS" },
  { nama: "Bluetooth Gaming Headset Corsair HS70" },
  { nama: "Bluetooth Gaming Controller SteelSeries Stratus" },
  { nama: "Bluetooth Gaming Mouse Logitech G903" },
  { nama: "Bluetooth Gaming Keyboard Razer BlackWidow" },
  { nama: "Bluetooth Gaming Headset Turtle Beach Elite Atlas" },
  { nama: "Bluetooth Gaming Controller Razer Raiju" },
  { nama: "Bluetooth Gaming Mouse Razer Basilisk" },
  { nama: "Bluetooth Gaming Keyboard Roccat Horde" },
  { nama: "Bluetooth Gaming Headset SteelSeries Arctis Pro" },
  { nama: "Bluetooth Gaming Controller Xbox Elite Wireless" },
  { nama: "Bluetooth Gaming Mouse Corsair Dark Core" },
  { nama: "Bluetooth Gaming Keyboard Logitech G910" },
  { nama: "Bluetooth Gaming Headset HyperX Cloud Alpha" },
  { nama: "Bluetooth Gaming Controller SteelSeries Arctis Pro" },
  { nama: "CPU AMD Ryzen 3" },
  { nama: "CPU Intel Core i9" },
  { nama: "CPU AMD Athlon" },
  { nama: "CPU Intel Pentium" },
  { nama: "CPU Apple A14 Bionic" },
  { nama: "CPU Qualcomm Snapdragon" },
  { nama: "CPU MediaTek Dimensity" },
  { nama: "CPU Samsung Exynos" },
  { nama: "CPU Huawei Kirin" },
  { nama: "VGA NVIDIA GeForce RTX Ti" },
  { nama: "VGA AMD Radeon RX Vega" },
  { nama: "VGA NVIDIA Quadro RTX" },
  { nama: "VGA AMD Radeon RX Navi" },
  { nama: "VGA NVIDIA GeForce GTX Super" },
  { nama: "VGA AMD Radeon Pro WX" },
  { nama: "VGA NVIDIA Tesla" },
  { nama: "VGA AMD Radeon RX XT" },
  { nama: "VGA NVIDIA GeForce GT" },
  { nama: "VGA AMD Radeon RX Pro" },
  { nama: "Motherboard ASUS TUF Gaming" },
  { nama: "Motherboard MSI B450" },
  { nama: "Motherboard Gigabyte B550" },
  { nama: "Motherboard ASRock Steel Legend" },
  { nama: "Motherboard Biostar Racing" },
  { nama: "Motherboard EVGA Z490" },
  { nama: "Motherboard Colorful iGame" },
  { nama: "Motherboard Zotac Gaming" },
  { nama: "Motherboard NZXT N7" },
  { nama: "Motherboard ROG Maximus" },
  { nama: "CPU AMD Ryzen 7 PRO" },
  { nama: "CPU Intel Core i7 XE" },
  { nama: "CPU AMD Ryzen Threadripper Pro" },
  { nama: "CPU Intel Core X Series" },
  { nama: "CPU Apple M1 Pro" },
  { nama: "CPU Qualcomm Snapdragon 8cx" },
  { nama: "CPU MediaTek Dimensity 2000" },
  { nama: "CPU Samsung Exynos 990" },
  { nama: "CPU Huawei Kirin 9000" },
  { nama: "VGA NVIDIA GeForce RTX 3080 Ti" },
  { nama: "VGA AMD Radeon RX 6900 XT" },
  { nama: "VGA NVIDIA Quadro RTX 8000" },
  { nama: "VGA AMD Radeon RX 6700 XT" },
  { nama: "VGA NVIDIA GeForce GTX 1660 Ti" },
  { nama: "VGA AMD Radeon Pro WX 8200" },
  { nama: "VGA NVIDIA Tesla V100" },
  { nama: "VGA AMD Radeon RX 6600 XT" },
  { nama: "VGA NVIDIA GeForce GT 1030" },
  { nama: "VGA AMD Radeon RX Pro W5700" },
  { nama: "Motherboard ASUS Prime" },
  { nama: "Motherboard MSI X570" },
  { nama: "Motherboard Gigabyte X570 Aorus" },
  { nama: "Motherboard ASRock Phantom Gaming" },
  { nama: "Motherboard Biostar Racing X570" },
  { nama: "Motherboard EVGA Z590" },
  { nama: "Motherboard Colorful iGame Z490" },
  { nama: "Motherboard Zotac Gaming X570" },
  { nama: "Motherboard NZXT N7 B550" },
  { nama: "Motherboard ROG Strix X570" },
  { nama: "CPU AMD Ryzen 9 PRO" },
  { nama: "CPU Intel Core i9 Extreme" },
  { nama: "CPU AMD Ryzen Threadripper Pro WX" },
  { nama: "CPU Intel Core Xeon" },
  { nama: "CPU Apple M2" },
  { nama: "CPU Qualcomm Snapdragon 8 Gen 1" },
  { nama: "CPU MediaTek Dimensity 3000" },
  { nama: "CPU Samsung Exynos 2100" },
  { nama: "CPU Huawei Kirin 9100" },
  { nama: "VGA NVIDIA GeForce RTX 3090 Ti" },
  { nama: "VGA AMD Radeon RX 7900 XT" },
  { nama: "VGA NVIDIA Quadro RTX 9000" },
  { nama: "VGA AMD Radeon RX 6800 XT" },
  { nama: "VGA NVIDIA GeForce GTX 1080 Ti" },
  { nama: "VGA AMD Radeon Pro WX 9100" },
  { nama: "VGA NVIDIA Tesla T4" },
  { nama: "VGA AMD Radeon RX 6500 XT" },
  { nama: "VGA NVIDIA GeForce GT 710" },
  { nama: "VGA AMD Radeon RX Pro W6800" },
  { nama: "Motherboard ASUS ROG Crosshair" },
  { nama: "Motherboard MSI MEG X570" },
  { nama: "Motherboard Gigabyte Z590 Aorus" },
  { nama: "Motherboard ASRock Taichi" },
  { nama: "Motherboard Biostar Racing Z490" },
  { nama: "Motherboard EVGA Z690" },
  { nama: "Motherboard Colorful iGame X570" },
  { nama: "Motherboard Zotac Gaming Z590" },
  { nama: "Motherboard NZXT N7 Z590" },
  { nama: "Motherboard ROG Maximus Z690" },
  { nama: "CPU AMD Ryzen 9" },
  { nama: "CPU Intel Core i7" },
  { nama: "CPU AMD Ryzen 7" },
  { nama: "CPU Intel Core i5" },
  { nama: "CPU AMD Ryzen 5" },
  { nama: "CPU Intel Core i3" },
  { nama: "CPU AMD Ryzen Threadripper" },
  { nama: "CPU Intel Xeon" },
  { nama: "CPU Apple M1" },
  { nama: "VGA NVIDIA GeForce RTX" },
  { nama: "VGA AMD Radeon RX" },
  { nama: "VGA NVIDIA GeForce GTX" },
  { nama: "VGA AMD Radeon Pro" },
  { nama: "VGA NVIDIA Quadro" },
  { nama: "VGA AMD Radeon Vega" },
  { nama: "VGA NVIDIA Titan" },
  { nama: "VGA AMD FirePro" },
  { nama: "Motherboard ASUS ROG Strix" },
  { nama: "Motherboard MSI MPG" },
  { nama: "Motherboard Gigabyte Aorus" }
];

export const satuan_barang = [
  {
    nama: "kg",
  },
  {
    nama: "pcs",
  },
  {
    nama: "liter",
  },
  {
    nama: "meter",
  }
];

export const harga_beli = [
  {
    nama: "masukkan harga_beli",
  },
];

export const status_barang = [
  {
    nama: 1,
  },
  {
    nama: 0,
  }
];
